Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,10 +52,22 @@ jobs:
         run: |
           python setup.py sdist bdist_wheel
 
-      # Step 6: Upload the wheel to GitHub Release
-      - name: Upload to GitHub Release
-        uses: ncipollo/release-action@v1
+      - name: Resolve Wheel Path
+        id: resolve_wheel
+        run: |
+          WHEEL_FILE=$(ls dist/freqtrade-*.whl | head -n 1)
+          if [ -z "$WHEEL_FILE" ]; then
+            echo "Wheel file not found in dist/ directory."
+            exit 1
+          fi
+          echo "Resolved wheel file: $WHEEL_FILE"
+          echo 'wheel='$WHEEL_FILE >> ${GITHUB_ENV}
+          echo 'basename='basename($WHEEL_FILE) >> ${GITHUB_ENV}
+
+      - name: Upload Release Asset
+        uses: actions/upload-release-asset@v1
         with:
-          artifacts: dist/*
-          replacesArtifacts: true
-          token: ${{ secrets.ACCESS_TOKEN }}
+          asset_path: ./${{ env.wheel }}
+          asset_name: ${{ env.basename }}
+          upload_url: ${{ github.event.release.upload_url }}
+          asset_content_type: application/octet-stream
